services:
  # Backend API (Rust)
  backend:
    build:
      context: ./viworks-backend
      dockerfile: Dockerfile
    container_name: viworks-backend-local
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - RUST_LOG=info
      - JWT_SECRET=local_development_jwt_secret_key
      - JWT_EXPIRATION=3600
      - BCRYPT_COST=12
      - CORS_ORIGINS=http://localhost:3000
      - ADMIN_PANEL_URL=http://localhost:3000
      - API_BASE_URL=http://localhost:8081
    networks:
      - viworks-local-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Frontend (Next.js)
  frontend:
    build:
      context: ./viworks-frontend
      dockerfile: Dockerfile
    container_name: viworks-frontend-local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8081
      - NEXT_PUBLIC_WS_URL=ws://localhost:8081
      - PORT=3000
    depends_on:
      - backend
    networks:
      - viworks-local-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  viworks-local-network:
    driver: bridge
