services:
  # Nginx Reverse Proxy (Public Network)
  nginx:
    image: nginx:alpine
    container_name: viworks-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/letsencrypt:ro
    networks:
      - viworks-public
      - viworks-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database (Internal Network Only)
  postgres:
    image: postgres:15-alpine
    container_name: viworks-postgres
    environment:
      POSTGRES_DB: viworks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-viworks_password_2024}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viworks-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d viworks"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache (Internal Network Only)
  redis:
    image: redis:7-alpine
    container_name: viworks-redis
    volumes:
      - redis_data:/data
    networks:
      - viworks-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend API Server (Internal Network Only)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: viworks-backend
    env_file:
      - ./env.production
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - viworks-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Next.js App (Internal Network Only)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: viworks-frontend
    env_file:
      - ./env.production
    depends_on:
      - backend
    networks:
      - viworks-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  # Public network - only nginx is exposed
  viworks-public:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: viworks-public
  
  # Internal network - all services communicate here
  viworks-internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: viworks-internal
    internal: true  # No external access
