name: viworks-backend
region: lon1
services:
- name: viworks-backend
  source_dir: /
  github:
    repo: viworks/viworks-backend
    branch: main
  run_command: ./viworks-admin-backend
  environment_slug: rust
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: JWT_SECRET
    value: your-super-secret-jwt-key-change-in-production
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: BCRYPT_ROUNDS
    value: "12"
  - key: RATE_LIMIT_WINDOW
    value: "900000"
  - key: RATE_LIMIT_MAX
    value: "100"
  - key: CORS_ORIGIN
    value: https://clownfish-app-hylwo.ondigitalocean.app
  - key: ADMIN_PANEL_URL
    value: https://clownfish-app-hylwo.ondigitalocean.app
  - key: PORT
    value: "8081"
