services:
  # Backend API (In-memory data)
  backend:
    image: viworks-admin-backend:latest
    container_name: viworks-admin-backend
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=local_development_jwt_secret_key
      - HOST=0.0.0.0
      - PORT=8081
      - RUST_LOG=info
      - JWT_EXPIRATION=3600
      - BCRYPT_COST=12
      - CORS_ORIGINS=http://localhost:3000
      - ADMIN_PANEL_URL=http://localhost:3000
      - API_BASE_URL=http://localhost:8081
    networks:
      - viworks-admin-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Frontend (Next.js)
  frontend:
    image: viworks-admin-frontend:latest
    container_name: viworks-admin-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8081
      - NEXT_PUBLIC_WS_URL=ws://localhost:8081
    depends_on:
      - backend
    networks:
      - viworks-admin-network
    restart: unless-stopped

networks:
  viworks-admin-network:
    driver: bridge
