services:
  # Enhanced Backend API
  backend:
    image: viworks-admin-backend:enhanced
    container_name: viworks-admin-backend-enhanced
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - RUST_LOG=info
    networks:
      - viworks-admin-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: viworks-admin-frontend-enhanced
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - viworks-admin-network
    restart: unless-stopped

networks:
  viworks-admin-network:
    driver: bridge
