name: viworks-frontend
region: lon1
services:
- name: viworks-frontend
  source_dir: /
  github:
    repo: viworks/viworks-frontend
    branch: main
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_API_URL
    value: https://viworks-backend-${APP_ID}.ondigitalocean.app
  - key: NEXT_PUBLIC_WS_URL
    value: wss://viworks-backend-${APP_ID}.ondigitalocean.app
  - key: PORT
    value: "3000"
