apiVersion: apps/v1
kind: Deployment
metadata:
  name: viworks-redis
  namespace: viworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viworks-redis
  template:
    metadata:
      labels:
        app: viworks-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: viworks-redis-service
  namespace: viworks
spec:
  selector:
    app: viworks-redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: viworks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
