name: Deploy ViWorks Agent to DigitalOcean

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_REGISTRY: registry.digitalocean.com
  IMAGE_NAME: viworks-agent

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust application
        run: |
          cargo build --release
          cargo test --release

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.alpine-production -t viworks-agent:test .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine-production
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DIGITALOCEAN_PROJECT_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DIGITALOCEAN_PROJECT_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ secrets.DIGITALOCEAN_PROJECT_NAME }}/${{ env.IMAGE_NAME }}:latest
            
            # Stop and remove old container
            docker stop viworks-agent || true
            docker rm viworks-agent || true
            
            # Run new container
            docker run -d \
              --name viworks-agent \
              --restart unless-stopped \
              --network viworks-internal \
              -p 8443:8443 \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -e RUST_LOG=info \
              -e AGENT_CONFIG=/etc/viworks/agent.toml \
              ${{ env.DOCKER_REGISTRY }}/${{ secrets.DIGITALOCEAN_PROJECT_NAME }}/${{ env.IMAGE_NAME }}:latest
            
            # Clean up old images
            docker image prune -f

      - name: Health check
        run: |
          sleep 30
          curl -f http://${{ secrets.DROPLET_HOST }}:8443/api/v1/health || exit 1
