[build]
# Enable incremental compilation for faster rebuilds
incremental = true

# Use multiple jobs for parallel compilation
jobs = 4  # Use 4 CPU cores for compilation

# Optimize for development speed
[profile.dev]
# Reduce debug info for faster compilation
debug = false
# Disable some optimizations for faster compilation
opt-level = 0
# Disable overflow checks for speed
overflow-checks = false

[profile.release]
# Keep optimizations for release builds
opt-level = 3
# Enable link-time optimization for better performance
lto = true
# Enable codegen units optimization
codegen-units = 1
