name: viworks-admin-panel
region: lon1
services:
- name: viworks-backend
  source_dir: /backend
  github:
    repo: viworks/viworks-admin-panel
    branch: main
  run_command: ./viworks-admin-backend
  environment_slug: rust
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: JWT_SECRET
    value: your-super-secret-jwt-key-change-in-production
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: BCRYPT_ROUNDS
    value: "12"
  - key: RATE_LIMIT_WINDOW
    value: "900000"
  - key: RATE_LIMIT_MAX
    value: "100"
  - key: CORS_ORIGIN
    value: https://viworks-frontend-${APP_ID}.ondigitalocean.app
  - key: ADMIN_PANEL_URL
    value: https://viworks-frontend-${APP_ID}.ondigitalocean.app
  - key: PORT
    value: "8081"

- name: viworks-frontend
  source_dir: /frontend
  github:
    repo: viworks/viworks-admin-panel
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_API_URL
    value: https://viworks-backend-${APP_ID}.ondigitalocean.app
  - key: NEXT_PUBLIC_WS_URL
    value: wss://viworks-backend-${APP_ID}.ondigitalocean.app
  - key: PORT
    value: "3000"
